import assert from 'node:assert/strict';
import {generate, parseScript, suppliedSource, askAI, slug} from '../generator/core.mjs';
import worker from '../generator/worker.mjs';
const F=globalThis.DeckFormat;
const transcript=Array.from({length:80},(_,i)=>`I need to brush up on lesson number ${i+1} before the trip.`).join('\n');
const selection=Array.from({length:50},(_,i)=>({front:transcript.split('\n')[i],word:'brush up on',cn:'温习；复习',ipa:'/brʌʃ ʌp ɒn/',trans:'旅行前我得复习这一课。',focus:'brush up on'}));
const note={meaning:'温习原先学过的内容。',pattern:'brush up on + 学科或技能',example:'I need to brush up on my French.',exampleCn:'我得温习一下法语。',grammar:'need to 后接动词原形；on 后接温习的内容。',note:'常用于重新熟悉已有知识。',words:[{word:'lesson',meaning:'课；一课的内容'}]};
const meta={kind:'series',show:'Example Show',season:2,episode:3,year:null};
const env={AI_BASE_URL:'https://ai.example/v1',AI_MODEL:'configured-model',AI_API_KEY:'test-api-secret',APP_TOKEN:'test-access-token-1234',ALLOWED_ORIGINS:'https://3280053419w-cloud.github.io'};
const respond=value=>new Response(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}]}),{headers:{'Content-Type':'application/json'}});
let calls=0;
const mock=async(url,options)=>{
  assert.equal(url,'https://ai.example/v1/chat/completions');assert.equal(options.headers.Authorization,'Bearer test-api-secret');
  const body=JSON.parse(options.body);assert.equal(body.model,'configured-model');assert.equal(body.response_format.type,'json_object');calls++;
  return calls===1?respond({showCn:'示例剧集',cards:selection}):respond({cards:Array.from({length:10},()=>note)});
};
const messages=[];
const payload=await generate({...meta,transcript},env,m=>messages.push(m),mock);
assert.equal(calls,6);assert.equal(payload.deck.cards.length,50);assert.equal(new Set(payload.deck.cards.map(c=>c.id)).size,50);assert.equal(payload.deck.sourceUrl,'');assert.equal(payload.deck.source,'用户提供字幕（集数由用户确认）');assert.match(messages.at(-1),/50\/50/);
assert.equal(F.validate(payload).deck.cards[0].grammar,note.grammar);
assert.equal(F.csv(payload).split('\n').length,55);
assert.equal(slug("It's Always Sunny in Philadelphia"),'its-always-sunny-in-philadelphia');
assert.throws(()=>F.input({...meta,episode:0}),/季数和集数/);
assert.throws(()=>F.validate({...payload,deck:{...payload.deck,cards:payload.deck.cards.slice(1)}}),/恰好/);
const duplicate=structuredClone(payload);duplicate.deck.cards[1].front=duplicate.deck.cards[0].front;assert.throws(()=>F.validate(duplicate),/重复/);
const invalid=structuredClone(payload);invalid.deck.cards[0].focus='invented phrase';assert.throws(()=>F.validate(invalid),/目标不在/);
const unrelated=structuredClone(payload);unrelated.deck.cards[0].words=[{word:'invented word',meaning:'错误词'}];assert.throws(()=>F.validate(unrelated),/不在对应台词/);
assert.equal(F.idFor(payload.deck),F.idFor({...payload.deck,show:'EXAMPLE SHOW'}));
assert.notEqual(F.idFor(payload.deck),F.idFor({...payload.deck,episode:4}));
assert.equal(F.input({kind:'movie',show:'Example Film',year:'2020'}).episode,0);
const page='<h1>Example Show S02E03 - Episode Script</h1><div class="scrolling-script-container">'+transcript.replace(/\n/g,'<br>')+'</div>';
const source=parseScript(page,meta,'https://www.springfieldspringfield.co.uk/view_episode_scripts.php?tv-show=example-show&episode=s02e03');assert.equal(source.text,transcript);
assert.throws(()=>parseScript(page,{...meta,show:'Wrong Show'},source.url),/片名/);
assert.throws(()=>parseScript(page,meta,source.url.replace('s02e03','s02e04')),/季集数/);
assert.throws(()=>parseScript('<h1>Example Show</h1>'+Array(100).fill('<a href="x">Navigation link</a>').join('\n'),meta,source.url),/足够/);
assert.throws(()=>suppliedSource('hello'),/字幕/);
let badCalls=0;
await assert.rejects(generate({...meta,transcript},env,()=>{},async()=>{badCalls++;const cards=structuredClone(selection);cards[0].front='This line never appears in the transcript.';return respond({cards});}),/核对的原句/);assert.equal(badCalls,1);
await assert.rejects(askAI(env,[],async()=>new Response('sensitive upstream detail',{status:401})),/密钥或权限/);
await assert.rejects(askAI(env,[],async()=>new Response(JSON.stringify({choices:[{finish_reason:'length'}]}))),/输出长度/);
await assert.rejects(askAI({...env,AI_API_KEY:''},[],mock),/未配置/);
const aborted=new AbortController();aborted.abort();await assert.rejects(generate({...meta,transcript},env,()=>{},async()=>{throw new Error('should not proceed');},aborted.signal));
const request=(path,options={})=>new Request('https://generator.example'+path,{...options,headers:{Origin:env.ALLOWED_ORIGINS,Authorization:'Bearer '+env.APP_TOKEN,...options.headers}});
assert.equal((await worker.fetch(request('/health'),env)).status,200);
assert.equal((await worker.fetch(request('/health',{headers:{Origin:'https://untrusted.example'}}),env)).status,403);
assert.equal((await worker.fetch(request('/health',{headers:{Authorization:'Bearer wrong'}}),env)).status,401);
assert.equal((await worker.fetch(request('/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}),env)).status,400);
assert.equal((await worker.fetch(request('/health'),{...env,APP_TOKEN:''})).status,503);
assert.equal((await worker.fetch(request('/generate',{method:'OPTIONS'}),env)).status,204);
calls=0;
const stream=await worker.fetch(request('/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...meta,transcript})}),{...env,FETCH:mock});
assert.equal(stream.headers.get('Access-Control-Allow-Origin'),env.ALLOWED_ORIGINS);
const wire=await stream.text(),events=wire.trim().split('\n').map(s=>JSON.parse(s));
assert.equal(events.at(-1).type,'result');assert.equal(events.at(-1).payload.deck.cards.length,50);assert.equal(wire.includes('test-api-secret'),false);assert.equal(wire.includes('test-access-token'),false);
console.log('Passed: 50-card generation pipeline, 6 compatible AI requests, source verification, validation, Anki export, authentication, CORS, and streamed responses.');
